#**Netflix Movies and TV Shows: An Exploratory Data Analysis. In this notebook, I will explore the Netflix dataset to understand content trends, popular genres, and the distribution of content across the globe.**

#  Netflix Exploratory Data Analysis (EDA) – Updated till 2025

## 🔹 Introduction
Netflix is one of the largest streaming platforms, offering thousands of Movies and TV Shows globally.  
This project analyzes Netflix data till **2025**, providing more updated insights than traditional datasets.

## 🔹 Objectives
- Clean and preprocess the dataset
- Explore patterns in Movies vs TV Shows
- Analyze trends across countries and years
- Study popular genres and ratings
- Derive insights on how Netflix’s strategy evolved till 2025

In [1]:
from google.colab import drive
import os

# 1. Mount Google Drive
drive.mount('/content/drive')

# 2. Set your GitHub Identity (Required for Green Dots)
!git config --global user.email "pankajbarathod9@gmail.com"
!git config --global user.name "Krishna3226"

# 3. Move to your Project Folder (Change 'MyProject' to your folder name)
%cd /content/drive/MyDrive/1230280501028 (1)/Projects/netflix-data-analysis

Mounted at /content/drive
/content/drive/MyDrive/1230280501028 (1)/Projects/netflix-data-analysis

## 🔹 Dataset Description
We have two separate CSV files:
- **Movies dataset**
- **TV Shows dataset**

Each dataset includes:
- `title` – Name of the content  
- `director`, `cast` – Key people involved  
- `country` – Origin country  
- `release_year` – Original release year  
- `date_added` – When added to Netflix  
- `rating` – Age rating (PG, R, TV-MA, etc.)  
- `duration` – Runtime (Movies) or Seasons (TV Shows)  
- `listed_in` – Genres  
- `description` – Short summary

In [2]:
#Importing Necessary Libararies
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

#Style for plots
sns.set_style('whitegrid')
plt.style.use('fivethirtyeight')

# Load the Netflix dataset
movies = pd.read_csv("/content/drive/MyDrive/1230280501028 (1)/Projects/netflix-data-analysis/netflix_movies_detailed_up_to_2025.csv")
tv_shows=pd.read_csv("/content/drive/MyDrive/1230280501028 (1)/Projects/netflix-data-analysis/netflix_tv_shows_detailed_up_to_2025.csv")

df=pd.concat([movies,tv_shows],axis=0)
df.columns
print("Shape of Dataset: ",df.shape)
df

Shape of Dataset:  (32000, 18)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average,budget,revenue
0,10192,Movie,Shrek Forever After,Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz, Antoni...",United States of America,2010-05-16,2010,6.380,NaN,"Comedy, Adventure, Fantasy, Animation, Family",en,A bored and domesticated Shrek pacts with deal...,203.893,7449,6.380,165000000.0,752600867.0
1,27205,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W...","United Kingdom, United States of America",2010-07-15,2010,8.369,NaN,"Action, Science Fiction, Adventure",en,"Cobb, a skilled thief who commits corporate es...",156.242,37119,8.369,160000000.0,839030630.0
2,12444,Movie,Harry Potter and the Deathly Hallows: Part 1,David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, T...","United Kingdom, United States of America",2010-11-17,2010,7.744,NaN,"Adventure, Fantasy",en,"Harry, Ron and Hermione walk away from their l...",121.191,19327,7.744,250000000.0,954305868.0
3,38757,Movie,Tangled,"Byron Howard, Nathan Greno","Mandy Moore, Zachary Levi, Donna Murphy, Ron P...",United States of America,2010-11-24,2010,7.600,NaN,"Animation, Family, Adventure",en,"Feisty teenager Rapunzel, who has long and mag...",111.762,11638,7.600,260000000.0,592461732.0
4,10191,Movie,How to Train Your Dragon,"Chris Sanders, Dean DeBlois","Jay Baruchel, Gerard Butler, Craig Ferguson, A...",United States of America,2010-03-18,2010,7.800,NaN,"Fantasy, Adventure, Animation, Family",en,As the son of a Viking leader on the cusp of m...,110.044,13259,7.800,165000000.0,494879471.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,284892,TV Show,Sammelanam,NaN,NaN,NaN,2025-02-20,2025,0.000,1 Seasons,"Comedy, Drama",te,Sammelanam is a gripping Telugu web series tha...,3.236,0,0.000,NaN,NaN
15996,277665,TV Show,Anne Shirley,NaN,"Honoka Inoue, Yasunori Matsumoto, Aya Nakamura...",Japan,2025-04-05,2025,0.000,1 Seasons,"Animation, Drama, Family",ja,It's depict Anne's growth from a girl to a wom...,3.558,0,0.000,NaN,NaN
15997,284972,TV Show,Le onde del passato,Giulio Manfredonia,"Anna Valle, Giorgio Marchesi, Irene Ferri, Fau...",NaN,2025-02-19,2025,10.000,1 Seasons,Drama,it,NaN,2.913,1,10.000,NaN,NaN
15998,284613,TV Show,AI히치하이커,NaN,NaN,NaN,2025-02-16,2025,0.000,1 Seasons,NaN,ko,NaN,2.787,0,0.000,NaN,NaN
15999,251815,TV Show,Alex & Laura's Saturday Night Takeaway,NaN,"Alex Bickerton, Lauren Blake",NaN,2025-02-15,2025,0.000,1 Seasons,"Comedy, Family",en,A gameshow hosted by Alex & Laura filled with ...,2.485,0,0.000,NaN,NaN

In [3]:
df.info()
#Checking Number of Missing Values in each Row
missing_values=df.isnull().sum()
print('\n Missing Values:\n','\n',missing_values[missing_values>0])

<class 'pandas.core.frame.DataFrame'>
Index: 32000 entries, 0 to 15999
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       32000 non-null  int64
 1   type          32000 non-null  object
 2   title         32000 non-null  object
 3   director      20903 non-null  object
 4   cast          30639 non-null  object
 5   country       29737 non-null  object
 6   date_added    32000 non-null  object
 7   release_year  32000 non-null  int64
 8   rating        32000 non-null  float64
 9   duration      16000 non-null  object
 10  genres        30919 non-null  object
 11  language      32000 non-null  object
 12  description   28662 non-null  object
 13  popularity    32000 non-null  float64
 14  vote_count    32000 non-null  int64
 15  vote_average  32000 non-null  float64
 16  budget        16000 non-null  float64
 17  revenue       16000 non-null  float64
dtypes: float64(5), int64(3), object(10)
memory usage: 5.6+ MB

 Missing Values:

 director       11097
cast            1361
country         2263
duration       16000
genres          1081
description     3338
budget         16000
revenue        16000
dtype: int64

In [4]:
df_sorted=df.sort_values(by='release_year',ascending=True)
df_sorted.iloc[1]

show_id                                                     73861
type                                                        Movie
title                                              A Serbian Film
director                                         Srđan Spasojević
cast            Srđan 'Žika' Todorović, Sergej Trifunović, Jel...
country                                                    Serbia
date_added                                             2010-06-16
release_year                                                 2010
rating                                                      5.471
duration                                                      NaN
genres                                    Crime, Horror, Thriller
language                                                       sr
description     Retired porn star Milos leads a normal family ...
popularity                                                 74.238
vote_count                                                   2018
vote_average                                                5.471
budget                                                        0.0
revenue                                                       0.0
Name: 14, dtype: object

In [5]:
df_sorted.reset_index(drop='True')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average,budget,revenue
0,38234,Movie,Undisputed III: Redemption,Isaac Florentine,"Scott Adkins, Mykel Shannon Jenkins, Mark Ivan...",United States of America,2010-04-17,2010,7.517,NaN,"Action, Thriller, Crime, Drama",en,"Russian inmate Boyka, now severely hobbled by ...",71.837,925,7.517,3000000.0,2.825480e+05
1,73861,Movie,A Serbian Film,Srđan Spasojević,"Srđan 'Žika' Todorović, Sergej Trifunović, Jel...",Serbia,2010-06-16,2010,5.471,NaN,"Crime, Horror, Thriller",sr,Retired porn star Milos leads a normal family ...,74.238,2018,5.471,0.0,0.000000e+00
2,12155,Movie,Alice in Wonderland,Tim Burton,"Mia Wasikowska, Johnny Depp, Anne Hathaway, He...",United States of America,2010-03-03,2010,6.600,NaN,"Family, Fantasy, Adventure",en,"Alice, now 19 years old, returns to the whimsi...",80.326,14114,6.600,200000000.0,1.025467e+09
3,24021,Movie,The Twilight Saga: Eclipse,David Slade,"Kristen Stewart, Robert Pattinson, Taylor Laut...",United States of America,2010-06-23,2010,6.204,NaN,"Adventure, Fantasy, Drama, Romance",en,Bella once again finds herself surrounded by d...,81.800,8829,6.204,68000000.0,6.984913e+08
4,10193,Movie,Toy Story 3,Lee Unkrich,"Tom Hanks, Tim Allen, Joan Cusack, Don Rickles...",United States of America,2010-06-16,2010,7.800,NaN,"Animation, Family, Comedy",en,"Woody, Buzz, and the rest of Andy's toys haven...",83.097,14847,7.800,200000000.0,1.067316e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31995,774370,Movie,Dog Man,Peter Hastings,"Peter Hastings, Pete Davidson, Lil Rel Howery,...",United States of America,2025-01-24,2025,7.700,NaN,"Family, Animation, Comedy, Action",en,When a faithful police dog and his human polic...,977.456,132,7.700,40000000.0,8.819214e+07
31996,1084199,Movie,Companion,Drew Hancock,"Sophie Thatcher, Jack Quaid, Lukas Gage, Megan...",United States of America,2025-01-22,2025,7.000,NaN,"Horror, Science Fiction, Thriller",en,During a weekend getaway at a secluded lakesid...,1283.362,610,7.000,10000000.0,3.448039e+07
31997,822119,Movie,Captain America: Brave New World,Julius Onah,"Anthony Mackie, Harrison Ford, Danny Ramirez, ...",United States of America,2025-02-12,2025,6.179,NaN,"Action, Thriller, Science Fiction",en,After meeting with newly elected U.S. Presiden...,1495.724,833,6.179,180000000.0,2.894057e+08
31998,1126166,Movie,Flight Risk,Mel Gibson,"Mark Wahlberg, Michelle Dockery, Topher Grace,...",United States of America,2025-01-22,2025,6.000,NaN,"Action, Thriller, Crime",en,A U.S. Marshal escorts a government witness to...,3320.616,350,6.000,25000000.0,4.042019e+07
31999,950396,Movie,The Gorge,Scott Derrickson,"Miles Teller, Anya Taylor-Joy, Sigourney Weave...",United States of America,2025-02-13,2025,7.785,NaN,"Romance, Science Fiction, Thriller",en,Two highly trained operatives grow close from ...,3876.006,1572,7.785,0.0,0.000000e+00

Here, 7 Columns are there which have Missing Values:
director(object),
cast(object),
country(object),
genre(object),
description(object),
budget(object),
revenue(object),



*   **Duration data is only available for TV Show. for Movies These field is Missing.**
*   **Budget and revenue data is only available for Movies. For TV
Shows, these fields are missing.**

## 🔹 Data Cleaning
Steps performed:
1. Handle missing values
2. Convert `date_added` into datetime, Extract useful feature `content_age`
3. Remove duplicates

## 1. Handle missing values

In [6]:
# df=df.drop(['season_num','movie_duration'],axis=1)

In [7]:
df_sorted=df_sorted.drop('duration',axis=1)

In [8]:
df_sorted.isnull().sum()

df_sorted=df_sorted.fillna({"director":"Unknown",'cast':"Unknown","country":"Unknown",'genres':"Unknown","description":"No Description Available"})

In [9]:
df_sorted['budget']=pd.to_numeric(df_sorted['budget'])

df_sorted['revenue']=pd.to_numeric(df_sorted['revenue'])


## 2. Convert `date_added` into datetime,Extract useful feature `year_added`, `content_age`

In [10]:
df_sorted['date_added']=pd.to_datetime(df_sorted['date_added'],errors='coerce')
df_sorted.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32000 entries, 15 to 15000
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       32000 non-null  int64
 1   type          32000 non-null  object
 2   title         32000 non-null  object
 3   director      32000 non-null  object
 4   cast          32000 non-null  object
 5   country       32000 non-null  object
 6   date_added    32000 non-null  datetime64[ns]
 7   release_year  32000 non-null  int64
 8   rating        32000 non-null  float64
 9   genres        32000 non-null  object
 10  language      32000 non-null  object
 11  description   32000 non-null  object
 12  popularity    32000 non-null  float64
 13  vote_count    32000 non-null  int64
 14  vote_average  32000 non-null  float64
 15  budget        16000 non-null  float64
 16  revenue       16000 non-null  float64
dtypes: datetime64[ns](1), float64(5), int64(3), object(8)
memory usage: 4.4+ MB

In [11]:
df_sorted['year_added']=df_sorted['date_added'].dt.year

In [12]:
df_sorted['content_age']=2026-df_sorted['year_added']

In [13]:
display(df_sorted[['year_added','content_age']])

       year_added  content_age
15           2010           16
14           2010           16
13           2010           16
12           2010           16
11           2010           16
...           ...          ...
15004        2025            1
15003        2025            1
15002        2025            1
15001        2025            1
15000        2025            1

[32000 rows x 2 columns]

## 3. Remove duplicates

In [14]:
duplicates=df_sorted.duplicated().sum()
duplicates

np.int64(0)

For TV Shows there are no such columns like revenue and budget. but in movies it is there.so there NaNs in tv shows.

In [15]:
profit=df_sorted['revenue']-df_sorted['budget']
ROI=profit/df_sorted['budget']
df_sorted['profit']=profit
df_sorted['ROI']=ROI
# df_sorted.head(15)

In [16]:
df_sorted['ROI']=df_sorted['ROI'].replace([np.inf,-np.inf],np.nan)

**Profit and ROI apply only to Movies**

In [17]:
profit_mean=df_sorted['profit'].mean()
loss = df_sorted['profit']<0
df_sorted['loss']=loss

In [18]:
df_sorted[df_sorted['loss'] == True]

,show_id,type,title,director,cast,country,date_added,release_year,rating,genres,...,popularity,vote_count,vote_average,budget,revenue,year_added,content_age,profit,ROI,loss
15,38234,Movie,Undisputed III: Redemption,Isaac Florentine,"Scott Adkins, Mykel Shannon Jenkins, Mark Ivan...",United States of America,2010-04-17,2010,7.517,"Action, Thriller, Crime, Drama",...,71.837,925,7.517,3000000.0,282548.0,2010,16,-2717452.0,-0.905817,True
71,37707,Movie,Splice,Vincenzo Natali,"Adrien Brody, Sarah Polley, Delphine Chanéac, ...","Canada, France, Germany",2010-06-03,2010,5.900,"Horror, Science Fiction",...,27.112,2273,5.900,26000000.0,0.0,2010,16,-26000000.0,-1.000000,True
107,25642,Movie,Ben 10 Alien Swarm,Alex Winter,"Ryan Kelley, Galadriel Stineman, Nathan Keyes,...",United States of America,2010-03-12,2010,6.100,"Adventure, Action, TV Movie, Science Fiction",...,20.878,343,6.100,40000000.0,0.0,2010,16,-40000000.0,-1.000000,True
105,49009,Movie,The Way Back,Peter Weir,"Ed Harris, Jim Sturgess, Saoirse Ronan, Colin ...","India, United Arab Emirates, United Kingdom, U...",2010-11-22,2010,7.000,"Drama, Adventure, History",...,21.501,1607,7.000,30000000.0,24200000.0,2010,16,-5800000.0,-0.193333,True
104,38199,Movie,Unthinkable,Gregor Jordan,"Samuel L. Jackson, Carrie-Anne Moss, Michael S...",United States of America,2010-06-14,2010,6.800,"Drama, Thriller",...,21.627,1224,6.800,15000000.0,0.0,2010,16,-15000000.0,-1.000000,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15042,881415,Movie,Love Me,"Andrew Zuchero, Sam Zuchero","Kristen Stewart, Steven Yeun",United States of America,2025-01-31,2025,5.917,"Science Fiction, Drama, Romance",...,108.376,12,5.917,2500000.0,215586.0,2025,1,-2284414.0,-0.913766,True
15035,447273,Movie,Snow White,Marc Webb,"Rachel Zegler, Gal Gadot, Andrew Burnap, Jerem...",United States of America,2025-03-19,2025,0.000,"Family, Fantasy",...,118.416,0,0.000,200000000.0,0.0,2025,1,-200000000.0,-1.000000,True
15027,950387,Movie,A Minecraft Movie,Jared Hess,"Jason Momoa, Jack Black, Danielle Brooks, Emma...","Sweden, United States of America, New Zealand",2025-04-02,2025,0.000,"Adventure, Fantasy, Family, Comedy",...,150.735,0,0.000,150000000.0,0.0,2025,1,-150000000.0,-1.000000,True
15014,696506,Movie,Mickey 17,Bong Joon Ho,"Robert Pattinson, Naomi Ackie, Mark Ruffalo, T...","United Kingdom, United States of America",2025-02-28,2025,7.600,"Science Fiction, Comedy, Drama",...,311.237,15,7.600,118000000.0,0.0,2025,1,-118000000.0,-1.000000,True
15005,1249289,Movie,Alarum,Michael Polish,"Scott Eastwood, Sylvester Stallone, Willa Fitz...",United States of America,2025-01-16,2025,5.792,"Action, Crime, Thriller",...,731.784,216,5.792,20000000.0,0.0,2025,1,-20000000.0,-1.000000,True

**Standard boolean columns in pandas (dtype bool) do not support NaN values. If you try to insert np.nan into a standard boolean column, pandas will usually convert the entire column to object dtype or float**

Converting 'loss' Data Type from 'bool' to 'boolean' dtype. This allows the column to hold True, False, and pd.NA (the pandas-specific version of NaN for non-floats).

In [19]:
df_sorted['loss']=df_sorted['loss'].astype('boolean')

In [20]:
df_sorted.loc[df_sorted['type']=='TV Show','loss']=pd.NA

**Only 44% data is there for Profit/loss calculation**

In [21]:
x=df_sorted[(df_sorted['revenue']==0) & (df_sorted['budget']==0)]
len(x)

9048

In [22]:
df_sorted.loc[df_sorted['type']=='TV Show']

,show_id,type,title,director,cast,country,date_added,release_year,rating,genres,...,popularity,vote_count,vote_average,budget,revenue,year_added,content_age,profit,ROI,loss
991,51434,TV Show,Duang Jai Akkanee,Unknown,"Nadech Kugimiya, Urassaya Sperbund, Prin Supar...",Thailand,2010-11-05,2010,0.0,"Comedy, Drama",...,13.212,0,0.0,NaN,NaN,2010,16,NaN,NaN,<NA>
990,73026,TV Show,The Firmament of the Pleiades,Wang Jun,"Yuko Tanaka, Wang He Yu, Yu Shaoqun, Yin Tao, ...","China, Japan",2010-01-02,2010,8.0,Drama,...,13.637,5,8.0,NaN,NaN,2010,16,NaN,NaN,<NA>
989,33036,TV Show,Memphis Beat,Unknown,"Celia Weston, Alfre Woodard, Jason Lee, Abraha...",United States of America,2010-06-22,2010,6.9,"Action & Adventure, Drama, Comedy",...,15.839,20,6.9,NaN,NaN,2010,16,NaN,NaN,<NA>
988,44308,TV Show,Scent of Rain in the Balkans,Ljubiša Samardžić,"Mirka Vasiljević, Aleksandra Bibić, Siniša Ubo...",Serbia,2010-12-11,2010,0.0,"Drama, War & Politics",...,13.265,0,0.0,NaN,NaN,2010,16,NaN,NaN,<NA>
987,34558,TV Show,Turn Back Time,Adam Hopkins,"Hugh Bonneville, Gregg Wallace, Susanna Reid, ...",United Kingdom,2010-11-02,2010,8.5,"Documentary, Reality",...,12.805,2,8.5,NaN,NaN,2010,16,NaN,NaN,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15972,285289,TV Show,비밀사이,Unknown,Unknown,Unknown,2025-02-27,2025,0.0,Unknown,...,5.094,0,0.0,NaN,NaN,2025,1,NaN,NaN,<NA>
15971,285290,TV Show,Visionaries,Unknown,Keanu Reeves,Unknown,2025-03-07,2025,0.0,Unknown,...,5.379,0,0.0,NaN,NaN,2025,1,NaN,NaN,<NA>
15970,285295,TV Show,The Hunt for Peter Tobin,Matt Pinder,Unknown,United Kingdom,2025-03-04,2025,0.0,"Documentary, Crime",...,5.379,0,0.0,NaN,NaN,2025,1,NaN,NaN,<NA>
15969,285297,TV Show,Julkkisten tietotoimisto,Unknown,Unknown,Finland,2025-03-05,2025,0.0,"Talk, Comedy",...,5.379,0,0.0,NaN,NaN,2025,1,NaN,NaN,<NA>
15968,285298,TV Show,Beauty,Unknown,"Jin Dazhong, Wang Xingchen",China,2025-02-27,2025,0.0,Drama,...,5.379,0,0.0,NaN,NaN,2025,1,NaN,NaN,<NA>

#**For Movies Which Have 0 revenue and budget ,profit=0 . Handle the Loss values Which are False**

In [23]:
df_sorted

,show_id,type,title,director,cast,country,date_added,release_year,rating,genres,...,popularity,vote_count,vote_average,budget,revenue,year_added,content_age,profit,ROI,loss
15,38234,Movie,Undisputed III: Redemption,Isaac Florentine,"Scott Adkins, Mykel Shannon Jenkins, Mark Ivan...",United States of America,2010-04-17,2010,7.517,"Action, Thriller, Crime, Drama",...,71.837,925,7.517,3000000.0,2.825480e+05,2010,16,-2717452.0,-0.905817,True
14,73861,Movie,A Serbian Film,Srđan Spasojević,"Srđan 'Žika' Todorović, Sergej Trifunović, Jel...",Serbia,2010-06-16,2010,5.471,"Crime, Horror, Thriller",...,74.238,2018,5.471,0.0,0.000000e+00,2010,16,0.0,NaN,False
13,12155,Movie,Alice in Wonderland,Tim Burton,"Mia Wasikowska, Johnny Depp, Anne Hathaway, He...",United States of America,2010-03-03,2010,6.600,"Family, Fantasy, Adventure",...,80.326,14114,6.600,200000000.0,1.025467e+09,2010,16,825467110.0,4.127336,False
12,24021,Movie,The Twilight Saga: Eclipse,David Slade,"Kristen Stewart, Robert Pattinson, Taylor Laut...",United States of America,2010-06-23,2010,6.204,"Adventure, Fantasy, Drama, Romance",...,81.800,8829,6.204,68000000.0,6.984913e+08,2010,16,630491347.0,9.271932,False
11,10193,Movie,Toy Story 3,Lee Unkrich,"Tom Hanks, Tim Allen, Joan Cusack, Don Rickles...",United States of America,2010-06-16,2010,7.800,"Animation, Family, Comedy",...,83.097,14847,7.800,200000000.0,1.067316e+09,2010,16,867316101.0,4.336581,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15004,774370,Movie,Dog Man,Peter Hastings,"Peter Hastings, Pete Davidson, Lil Rel Howery,...",United States of America,2025-01-24,2025,7.700,"Family, Animation, Comedy, Action",...,977.456,132,7.700,40000000.0,8.819214e+07,2025,1,48192145.0,1.204804,False
15003,1084199,Movie,Companion,Drew Hancock,"Sophie Thatcher, Jack Quaid, Lukas Gage, Megan...",United States of America,2025-01-22,2025,7.000,"Horror, Science Fiction, Thriller",...,1283.362,610,7.000,10000000.0,3.448039e+07,2025,1,24480388.0,2.448039,False
15002,822119,Movie,Captain America: Brave New World,Julius Onah,"Anthony Mackie, Harrison Ford, Danny Ramirez, ...",United States of America,2025-02-12,2025,6.179,"Action, Thriller, Science Fiction",...,1495.724,833,6.179,180000000.0,2.894057e+08,2025,1,109405738.0,0.607810,False
15001,1126166,Movie,Flight Risk,Mel Gibson,"Mark Wahlberg, Michelle Dockery, Topher Grace,...",United States of America,2025-01-22,2025,6.000,"Action, Thriller, Crime",...,3320.616,350,6.000,25000000.0,4.042019e+07,2025,1,15420193.0,0.616808,False
15000,950396,Movie,The Gorge,Scott Derrickson,"Miles Teller, Anya Taylor-Joy, Sigourney Weave...",United States of America,2025-02-13,2025,7.785,"Romance, Science Fiction, Thriller",...,3876.006,1572,7.785,0.0,0.000000e+00,2025,1,0.0,NaN,False

**Where vote_count was zero, both rating and vote_average were replaced with NaN because a rating and average cannot exist without any votes. Keeping 0.0 would corrupt any rating-based analysis.**

In [24]:
mask_for_rating_avg_votes = (df_sorted['rating']==0.0) & (df_sorted['vote_count']==0)
df_sorted.loc[mask_for_rating_avg_votes,['rating','vote_average']]=np.nan

In [25]:
df_sorted.loc[(df_sorted['rating']==0.0) & (df_sorted['vote_count']==0)]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, genres, language, description, popularity, vote_count, vote_average, budget, revenue, year_added, content_age, profit, ROI, loss]
Index: []

[0 rows x 22 columns]

In [26]:
df_sorted

,show_id,type,title,director,cast,country,date_added,release_year,rating,genres,...,popularity,vote_count,vote_average,budget,revenue,year_added,content_age,profit,ROI,loss
15,38234,Movie,Undisputed III: Redemption,Isaac Florentine,"Scott Adkins, Mykel Shannon Jenkins, Mark Ivan...",United States of America,2010-04-17,2010,7.517,"Action, Thriller, Crime, Drama",...,71.837,925,7.517,3000000.0,2.825480e+05,2010,16,-2717452.0,-0.905817,True
14,73861,Movie,A Serbian Film,Srđan Spasojević,"Srđan 'Žika' Todorović, Sergej Trifunović, Jel...",Serbia,2010-06-16,2010,5.471,"Crime, Horror, Thriller",...,74.238,2018,5.471,0.0,0.000000e+00,2010,16,0.0,NaN,False
13,12155,Movie,Alice in Wonderland,Tim Burton,"Mia Wasikowska, Johnny Depp, Anne Hathaway, He...",United States of America,2010-03-03,2010,6.600,"Family, Fantasy, Adventure",...,80.326,14114,6.600,200000000.0,1.025467e+09,2010,16,825467110.0,4.127336,False
12,24021,Movie,The Twilight Saga: Eclipse,David Slade,"Kristen Stewart, Robert Pattinson, Taylor Laut...",United States of America,2010-06-23,2010,6.204,"Adventure, Fantasy, Drama, Romance",...,81.800,8829,6.204,68000000.0,6.984913e+08,2010,16,630491347.0,9.271932,False
11,10193,Movie,Toy Story 3,Lee Unkrich,"Tom Hanks, Tim Allen, Joan Cusack, Don Rickles...",United States of America,2010-06-16,2010,7.800,"Animation, Family, Comedy",...,83.097,14847,7.800,200000000.0,1.067316e+09,2010,16,867316101.0,4.336581,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15004,774370,Movie,Dog Man,Peter Hastings,"Peter Hastings, Pete Davidson, Lil Rel Howery,...",United States of America,2025-01-24,2025,7.700,"Family, Animation, Comedy, Action",...,977.456,132,7.700,40000000.0,8.819214e+07,2025,1,48192145.0,1.204804,False
15003,1084199,Movie,Companion,Drew Hancock,"Sophie Thatcher, Jack Quaid, Lukas Gage, Megan...",United States of America,2025-01-22,2025,7.000,"Horror, Science Fiction, Thriller",...,1283.362,610,7.000,10000000.0,3.448039e+07,2025,1,24480388.0,2.448039,False
15002,822119,Movie,Captain America: Brave New World,Julius Onah,"Anthony Mackie, Harrison Ford, Danny Ramirez, ...",United States of America,2025-02-12,2025,6.179,"Action, Thriller, Science Fiction",...,1495.724,833,6.179,180000000.0,2.894057e+08,2025,1,109405738.0,0.607810,False
15001,1126166,Movie,Flight Risk,Mel Gibson,"Mark Wahlberg, Michelle Dockery, Topher Grace,...",United States of America,2025-01-22,2025,6.000,"Action, Thriller, Crime",...,3320.616,350,6.000,25000000.0,4.042019e+07,2025,1,15420193.0,0.616808,False
15000,950396,Movie,The Gorge,Scott Derrickson,"Miles Teller, Anya Taylor-Joy, Sigourney Weave...",United States of America,2025-02-13,2025,7.785,"Romance, Science Fiction, Thriller",...,3876.006,1572,7.785,0.0,0.000000e+00,2025,1,0.0,NaN,False

In [43]:
contrib=df_sorted.groupby('country')['title'].count().reset_index()
contrib.columns=['country','content_count']
display(contrib.sort_values('content_count',ascending=False))

                                                country  content_count
1622                           United States of America           7760
1211                                              Japan           2587
1735                                            Unknown           2263
545                                               China           2004
1453                                        South Korea           1999
...                                                 ...            ...
1737                                 Uruguay, Argentina              1
1734                United States of America, Venezuela              1
1732   United States of America, United Kingdom, Serbia              1
1731   United States of America, United Kingdom, Mexico              1
1730  United States of America, United Kingdom, Mala...              1

[1746 rows x 2 columns]

In [28]:
# !git add .
# !git commit -m "Done work with All Cleaning Steps."
# !git push origin main